#!/bin/sh
if [ ! -e /etc/xml/catalog ]; then
    xmlcatalog --noout --create /etc/xml/catalog
fi

xmlcatalog --noout --add "rewriteSystem" \
    "http://docbook.sourceforge.net/release/xsl/1.79.1" \
    "/share/xml/docbook/xsl-stylesheets-1.79.1" \
    /etc/xml/catalog

xmlcatalog --noout --add "rewriteURI" \
    "http://docbook.sourceforge.net/release/xsl/1.79.1" \
    "/share/xml/docbook/xsl-stylesheets-1.79.1" \
    /etc/xml/catalog &&

xmlcatalog --noout --add "rewriteSystem" \
    "http://docbook.sourceforge.net/release/xsl/current" \
    "/share/xml/docbook/xsl-stylesheets-1.79.1" \
    /etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
    "http://docbook.sourceforge.net/release/xsl/current" \
    "/share/xml/docbook/xsl-stylesheets-1.79.1" \
    /etc/xml/catalog
